#!/bin/bash

if [[ "$1" == "" ]]
then
    echo "You should specify a tag message"
    echo "Usage: $0 'your message here'"
    exit 1
fi

MAJOR=3
MINOR=0

# Updates the revision numbers and tags a revision in the git repository.
REVISION=`cat CURRENT_REVISION`
REVISION=$(($REVISION+1))
echo $REVISION > CURRENT_REVISION
git add CURRENT_REVISION
git commit -m "Tagging revision $REVISION"
git tag -s "v${MAJOR}.${MINOR}.${REVISION}" -m "$1"
